### PR TITLE
Expose convert and pad bool for Words conversion

### PR DESCRIPTION
**Pull request by junderw**

### CODE REVIEW

**Comment by dcousens** [comment]
@junderw could you please provide the test data / requirement that you had?

**Comment by junderw** [comment]
In decoding the payment request, there are a lot of parts where I have to use fromWords with padding.

since lnd and all implementations right-pad 0 bits to meet the nearest 5 bits when encoding 8 bit data (toWords) in order to reverse this I need to use fromWords WITH padding, then check if the length of the words x 5 % 8 == 0, if false, I drop off the last byte since it will always be 0x00. if true, I leave as is. (in this case fromWords WITHOUT padding would have passed without problem)

``` javascript
const wordsTrimmedToBuffer = (words) => {
  let buffer = Buffer.from(convert(words, 5, 8, true))
  if (words.length * 5 % 8 !== 0) {
    buffer = buffer.slice(0,-1)
  }
  return buffer
}
```

This is my work-around in bolt11

**Comment by junderw** [comment]
perhaps another function might be necessary:

fromWordsAndTrim (the assumption being the input words were originally created by padding a buffer to 5 bits)

or maybe it should be an arg of fromWords.... `trim` (bool) or something

**Comment by junderw** [comment]
I think the trim bool might be sufficient... but having the convert function exposed is convenient.

**Comment by dabura667** [comment]
hmmm... maybe the trim bool should be:

falsey == pad to nearest byte boundary (like my example)
truey == pad to nearest byte and chop off the last byte (assuming the input words were padded from a buffer)

fromWords failing when it's not exactly a common multiple of 5 and 8 when toWords has no problem with assuming to pad is kinda silly imo.

**Comment by dcousens** [comment]
I'll merge this after I have time to review the use case in Bolt11, if that is OK?

**Comment by junderw** [comment]
I guess it's not too bad. I just wanted to get rid of duplicate code, but from bech32 repo perspective this change is not really necessary. So I withdraw.

**Pull request closed without merging**
