### PR TITLE
Add unsafe functions

### PR DESCRIPTION
**Pull request by fanatid**
Issue: #23 

@dcousens let me know if you want continue with this changes and I add additional tests
not so good solution as it was expected

### CODE REVIEW

**Comment by dcousens** [comment]
I'll have a think about this.

> not so good solution as it was expected

Agreed,  but,  you did well with what you had.

**Comment by dcousens** [comment]
Looking back at it,  it isn't that bad.
Returning strings as `Errors` feels odd,  but,  we could do error codes?

**Comment by dcousens** [comment]
@fanatid we can generalize the error,  `'Unknown character in ' + str`

**Comment by fanatid** [comment]
In this case, you will need publish new major version :)
Are you okay with this?

**Comment by dcousens** [comment]
@fanatid damn you kids putting exception messages as part of the public API.  I don't mind.

**Comment by dcousens** [comment]
@fanatid do it :+1:

**Comment by fanatid** [comment]
@dcousens I fixed coverage and `convert` function, can you review?

**Comment by dcousens** [comment]
This looks good to go.
@fanatid did you still need it?

**Comment by fanatid** [comment]
Hey Daniel, sorry for delay. Yes, I still would like to see and use `unsafe` functions.

**Comment by junderw** [comment]
It looks like @fanatid stayed with the old Errors, so this isn't backwards incompatible.

I will bump minor version for this.

**Pull request merged**
